### ISSUE TITLE
No german umlauts in program titles and EPG data

### ISSUE THREAD

**Issue by lentferj** [janbar/xbmc-pvr-addons#30]
mythtv 0.27.3, latest PVR mythtv addon and Kodi 14 RC3. No german umlauts (öäü) and "sharp s" (ß) are displayed in program titles and EPG data. Kodi does display umlauts for e.g. music files and movie files so I think it#s a plugin problem. Also mythtv displays them e.g. via mythweb.

**Comment by Muiluutes** [comment]
I'm having the same problem, using mythtv 0.27.4 and and kodi 14.1.
Database is utf8 and when accessing epg data using web browser and the provided url (http://server:6544/Guide/GetProgramG...) characters are shown correctly.

**Comment by Muiluutes** [comment]
Problem was faulty /etc/locale.conf on the mythtv server.

**Comment by natronch** [comment]
I do have the same problem.

The MySql Server is set to UTF-8:

> Server characterset:	utf8
> Db     characterset:	utf8
> Client characterset:	utf8
> Conn.  characterset:	utf8

The locale on the backend:

> LANG=en_US.UTF-8
> LANGUAGE=en_US:en
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=en_US.UTF-8

And on the frontend:

> LANG=en_US.UTF-8
> LANGUAGE=en_US:en
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=en_US.UTF-8

The collation of the mythconverg tables is "utf8_general_ci"

A wget to the service api shows the "umlauts". Also, it did work with the old cmyth plugin.

Any Idea what else could be wrong?

**Comment by natronch** [comment]
Never mind, I found the cause: In my case, mythbackend was running with locale "POSIX" even though the system (Ubuntu) had set it to UTF-8. Setting the local prior starting the backend with upstart did solve the problem for me.

**Comment by janbar** [comment]
As i said before, in cmyth addon i had configured collation of mysql session with UTF8. Now the new addon doesn't connect to DB anymore. The collation is handle by backend server itself and it transfers data throw JSON messages to the addon. All messages must to be correctly encoded: to do that you have to fix backend configuration.
