### ISSUE TITLE
Kodi segfault/restart on Raspberry Pi 2

### ISSUE THREAD

**Issue by novalis111** [janbar/xbmc-pvr-addons#34]
Hi, there's a Bug which causes kodi to restart after getting the EPG/Channel Data from MythTV Backend. I have tried with OE + xbian (latest) with MythTV 0.27+fixes (latest), but no luck. This only seems to happen on the new Raspberry Pi 2 Model (1 Gig Ram, 4 Cores ARM CPU)

Dump with Stacktrace is here: http://xbmclogs.com/show.php?id=417502

taken from this thread:

http://forum.kodi.tv/showthread.php?tid=217563

It refers to OE, but the problem exists in xbian (and probably others) as well.

Regards,
Ingo

**Comment by i5tvan** [comment]
I experienced the same issue.
After enabling the addon the EPG data is gathered then RPI2 reboots.
EPG data updates upon reload, so get stuck with rolling reboots.

I tried the MythTV plugin on Raspbmc final (manual update to support RPI2), OSMC Alpha 4, and openELEC 5.0.1

Experienced the same issue with each flavour.

**Comment by schnitzengiggle** [comment]
+1 here. Kodi restarts or hangs. Last entry on log (tail -f via ssh) seems always to be connected to GetTimers:

19:34:28 T:1814606912   DEBUG: AddOnLog: MythTV PVR Client: GetTimers
19:34:28 T:1814606912   DEBUG: AddOnLog: MythTV PVR Client: GetTimers ## - State: -1 - ##

19:34:34 T:1695880256    INFO: AddOnLog: MythTV PVR Client: GetRecordingsAmount: No recording
19:34:34 T:1822753856   DEBUG: AddOnLog: MythTV PVR Client: GetTimers

19:34:40 T:1823609920   DEBUG: AddOnLog: MythTV PVR Client: GetTimers
19:34:40 T:1823609920   DEBUG: AddOnLog: MythTV PVR Client: GetTimers ## - State: -1 - ##

Can most easily be reproduced by resetting the PVR database, thus triggering EPG loading.
Pi2, OE 5.0.2, MythTV 0.27.4+.

**Comment by Enough64** [comment]
+1 here. Kodi restarts/hangs. Tried latest OE with the latest version of plugin (1.12.1 from owncloud)
PI2, OE 5.0.3, MythTV 0.27.4+

**Comment by janbar** [comment]
HI, i would need a backtrace (core) to anderstand what happening. Anyone could provide one ?

**Comment by janbar** [comment]
If no valid backtrace, i need someone to compile the lib "cppmyth" from my repo on the RPi2 and launch the cppmythtest program: ./test/cppmythtest <batckend IP>
Anyone ?

**Comment by MikeB2013** [comment]
I have posted some more crash logs see http://forum.kodi.tv/showthread.php?tid=198833&pid=1924806#pid1924806       post #703

Maybe there is more information in these.

Mike

**Comment by rkershenbaum** [comment]
Yes, this only occurs on Rpi2, not on the original Rpi.

**Comment by MikeB2013** [comment]
Janbar

Running ./test/cppmythtest "sometimes" results in Segmentation fault at Guide ChanId at random channelids. The "sometimes" varies between successive runs and 1 in 10. 

Tests done on osmc (debian Jessie based) and Raspbian (debian Wheezy based).
Both give the random segmenetation faults.
Cannot do on OE - no native build system.

Mike

**Comment by janbar** [comment]
So we can reproduce the crash outside Kodi now. It is a good point. When compiling 'cppmyth' have you see any message like "unknown architecture, atomic increment is not..." ?

**Comment by MikeB2013** [comment]
@janbar 
No compiler messages, apart from the usual 
/tmp/ccMcrDMj.s:36: Warning: swp{b} use is deprecated for ARMv6 and ARMv7

Mike

**Comment by janbar** [comment]
hmmm, it is hot. This warning is generated in atomic.h

**Comment by janbar** [comment]
I will do a change soon in 'cppmyth' for ARMv6. I let you know.

**Comment by janbar** [comment]
@MikeB2013 , I pushed a new commit in branch master of 'cppmyth' to handle ARMv6, ARMv7. Please could you pull it and retry test.

**Comment by rkershenbaum** [comment]
Could someone please compile this for OpenELEC 5, and post a link?  I'd be happy to test a compiled version on my Rpi2.

**Comment by MikeB2013** [comment]
@janbar 
Tried but it will not make:
pi@raspberrypi ~/janbar/build $ make
Scanning dependencies of target cppmyth
[  3%] Building CXX object cppmyth/CMakeFiles/cppmyth.dir/src/private/mythdto/mythdto.cpp.o
In file included from /home/pi/janbar/build/cppmyth/cppmyth/src/private/mythdto/../../mythsharedptr.h:25:0,
                 from /home/pi/janbar/build/cppmyth/cppmyth/src/private/mythdto/../../mythtypes.h:25,
                 from /home/pi/janbar/build/cppmyth/cppmyth/src/private/mythdto/version.h:25,
                 from /home/pi/janbar/build/cppmyth/cppmyth/src/private/mythdto/mythdto75.h:26,
                 from /home/pi/janbar/build/cppmyth/cppmyth/src/private/mythdto/mythdto.cpp:23:
/home/pi/janbar/build/cppmyth/cppmyth/src/private/mythdto/../../atomic.h: In function 'unsigned int atomic_increment(atomic_t*)':
/home/pi/janbar/build/cppmyth/cppmyth/src/private/mythdto/../../atomic.h:157:14: error: '__valp' was not declared in this scope
/home/pi/janbar/build/cppmyth/cppmyth/src/private/mythdto/../../atomic.h: In function 'unsigned int atomic_decrement(atomic_t*)':
/home/pi/janbar/build/cppmyth/cppmyth/src/private/mythdto/../../atomic.h:273:14: error: '__valp' was not declared in this scope
cppmyth/CMakeFiles/cppmyth.dir/build.make:54: recipe for target 'cppmyth/CMakeFiles/cppmyth.dir/src/private/mythdto/mythdto.cpp.o' failed
make[2]: *** [cppmyth/CMakeFiles/cppmyth.dir/src/private/mythdto/mythdto.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'cppmyth/CMakeFiles/cppmyth.dir/all' failed
make[1]: *** [cppmyth/CMakeFiles/cppmyth.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by janbar** [comment]
I missed something... I am checking.

**Comment by janbar** [comment]
@MikeB2013 , i made a typo error. Sorry. Could you pull again and retry ? Thanks

**Comment by janbar** [comment]
Also, this last make error, confirms cpu architecture is ARMv6 or next.

**Comment by MikeB2013** [comment]
@janbar 
Works!

Just run the test in a loop 100 times on Raspian against mythtv 0.27.4 fixes no errors.plus a few manual runs against mythtv 0.28pre, again no errors.

Also did a few manual runs against mythtv 0.28pre from Ubuntu X64 again no errors

Mike

**Comment by MikeB2013** [comment]
just for completeness:

Raspian on the RPi2 is running armv7 kernel
Linux raspberrypi 3.18.7-v7+ #755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015 armv7l GNU/Linux

gcc used 
gcc (Debian 4.6.3-14+rpi1) 4.6.3

file cppmythtest 
cppmythtest: ELF 32-bit LSB executable, ARM, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=0x4b636863613f73d4f629fd2ee636b7cd2c94fe85, not stripped

Mike

**Comment by janbar** [comment]
Great. Thanks @MikeB2013 . So now this evening (here it is 18:35) i push the update to the addon repository.

**Comment by janbar** [comment]
Fixed and merged to helix, gotham branches.

**Comment by MilhouseVH** [comment]
I'll include this in tonight's RPi/RPi2 test builds of OpenELEC.

**Comment by rkershenbaum** [comment]
Is a compiled version of the addon for Rpi2 available for download anywhere?

**Comment by janbar** [comment]
@rkershenbaum , You can download one from  https://www.canneasucre.org/owncloud/public.php?service=files&t=5f9f8b8e455bbdd3d0e95f4750925043&path=%2Fhelix%2FOpenELEC-5.0
waiting @MilhouseVH includes a fix.

**Comment by rkershenbaum** [comment]
Works perfectly on my Rpi2 with OpenELEC 5.03.  Thanks!

**Comment by MilhouseVH** [comment]
The fix is in build #0213:

http://forum.kodi.tv/showthread.php?tid=211501&pid=1926345#pid1926345

**Comment by MilhouseVH** [comment]
@janbar - are you planning on sending a request upstream, as OpenELEC will need this.

**Comment by Enough64** [comment]
Just to complete: to no surprise it also works on xbian/raspbian.

**Comment by janbar** [comment]
@MilhouseVH ,
I made this PR https://github.com/opdenkamp/xbmc-pvr-addons/pull/431 to Opdenkamp.
Do you need something else ?

**Comment by janbar** [comment]
@MilhouseVH , the PR contains fixes to:

- Support protocol MythTV 0.28-pre:84
- Support protocol MythTV 0.28-pre:85
- Fix C mangling issue: replace jansson by sajson
- Support ARMV6 , ARMV7 Atomic primitives
- Support for RPi2 architecture (ARMv7)
- fix valgrind issue

**Comment by janbar** [comment]
@MilhouseVH , 
I made the PR https://github.com/opdenkamp/xbmc-pvr-addons/pull/432 to upstream/master (I*** 15.0)

**Comment by MilhouseVH** [comment]
That's a lot more changes than I was expecting (it's a shame the ARMv6/ARMv7 changes aren't a separate commit), but now it's up to OpenELEC to cherry pick or wait for opdenkamp to merge etc. Many thanks.
