### ISSUE TITLE
Addon goes to incorrect directory level if "exit" used while "Working" spinner is active

### ISSUE THREAD

**Issue by rkershenbaum** [janbar/xbmc-pvr-addons#35]
If you delete a recording and hit "backspace" or "exit" while the "Working" spinner is still active, the screen goes to the ".." item, instead of to the correct directory level.

Hitting "exit" again does nothing at that point. The only way to get back to the main screen is to open the Options menu on the left, and select a screen other than the "Recordings" screen. Then "exit" will take you to the main Kodi screen.

Just a minor irritation, but probably something that should be fixed in a future update.

I've observed this with several versions of the addon, including the current one, 1.12.1 in Windows. A similar behavior occurs with OpenELEC.

**Comment by allan87** [comment]
This also happens intermittently on my Pi when exiting from a shows subfile, although I had not recognized that it arises when the working spinner is active.

**Comment by janbar** [comment]
Related to Kodi/XBMC issue. Please report to their respective project.
